kind: pipeline
type: docker
name: default
steps:
  - name: greeting
    image: test
    commands:
-ENV TZ=Asia/Shanghai
-ADD ht-eureka-0.0.1-SNAPSHOT.jar app.jar
-RUN bash -c 'touch /app.jar'
-ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=dev",  "-jar","/app.jar"]
-echo success



